### PR TITLE
changed Google+ mentions to Google

### PR DESCRIPTION
**Pull request by vijay-qlogic**

### CODE REVIEW

**Comment by mattwhisenhunt** [comment]
Shouldn't this be Blogger not Google?

**Comment by vijay-qlogic** [comment]
@mattwhisenhunt I think I misunderstood the Issue.

**Comment by mattwhisenhunt** [comment]
It's a good change. In this case I just think Blogger would have a bit more meaning.

**Comment by jdpedrie** [comment]
@vijay-qlogic any update?

**Comment by dwsupplee** [comment]
It's been awhile, I'm going to close this out.

**Pull request closed without merging**
