### PR TITLE
docs: fix invalid parameter type-hint for nextChunk

### PR DESCRIPTION
**Pull request by davidbrnovjak**
Pull request https://github.com/googleapis/google-api-php-client/pull/1872 adds some parameter type hints to code

For parameter `$chunk` in  `MediaFileUpload::nextChunk` it specifies a `bool` type but `string` should be also accepted because the implementation treats this parameter as it a string is.

### CODE REVIEW

**Comment by davidbrnovjak** [comment]
@googlebot I signed it!

**Comment by davidbrnovjak** [comment]
@googlebot I signed it!

**Comment by davidbrnovjak** [comment]
@googlebot I signed it!

**Comment by jdpedrie** [comment]
@davidbrnovjak make sure your commit is attached to the email you used to sign the CLA: https://help.github.com/articles/setting-your-email-in-git/

You can [amend the commit](https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit) and reset the owner. Then force-push back to github and trigger the CLA bot again.

**Comment by davidbrnovjak** [comment]
@googlebot I signed it!

**Comment by davidbrnovjak** [comment]
@googlebot I signed it!

**Comment by davidbrnovjak** [comment]
> 
> 
> @davidbrnovjak make sure your commit is attached to the email you used to sign the CLA: https://help.github.com/articles/setting-your-email-in-git/
> 
> You can [amend the commit](https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit) and reset the owner. Then force-push back to github and trigger the CLA bot again.

Thanks 👍

**Pull request merged**
