### PR TITLE
Optimize `Model::camelCase()`

### PR DESCRIPTION
**Pull request by WinterSilence**

### CODE REVIEW

**Comment by bshaffer** [comment]
I appreciate this PR, but since this library has been around a very long time, Id rather not risk changing something this fundamental unless the benefits are very clear. For this change, I do not think the optimizations would be significant enough to justify the risk.

**Comment by WinterSilence** [comment]
@bshaffer what risks are you talking about? tests work fine

**Comment by bshaffer** [comment]
Yes but as we both know, it's possible for tests to miss things. Thanks again for your contribution.

**Comment by WinterSilence** [comment]
@bshaffer based on this logic, any change is impossible. it's wrong way, right way - extend test to covering more cases.

**Pull request closed without merging**
