### PR TITLE
Update Model

### PR DESCRIPTION
**Pull request by WinterSilence**

### CODE REVIEW

**Comment by stephanvierkant** [comment]
Can you explain why this change is an improvement? Does this fix a bug?

**Comment by WinterSilence** [comment]
@stephanvierkant no, it's only faster & shortest

**Comment by bshaffer** [comment]
LGTM but you'll need to sign the SLA

**Review by bshaffer — APPROVED** [review]

**Comment by WinterSilence** [comment]
@bshaffer i'm don't know how fix it now

**Review by Jsonapk — APPROVED** [review]
very interesting .very awesoma

**Pull request closed without merging**
