### PR TITLE
feat: support phpseclib3

### PR DESCRIPTION
**Pull request by kylekatarnls**
- Allow to install `phpseclib/phpseclib` with no composer conflicts.
- Adapt `Verify` class to new phpseclib classes and methods.

### CODE REVIEW

**Review by bryanlaura736 — APPROVED** [review]

**Review by bshaffer — COMMENTED** [review]
This is great! Thank you for this!

I don't believe the current test suite covers `phpseclib:~2.0`. I'll try to get a PR in today to fix that, and once I can conform that's being tested this will be good to merge.

Thanks again.

**Comment by kylekatarnls** [comment]
`phpseclib3` namespace does not exist, so enforcing the installation of phpseclib 2 in an environment on GitHub Actions will work just fine (100% equivalent to current state)

**Comment by kylekatarnls** [comment]
I see you just dropped PHP 5.4 and 5.5, 🚀 I'll will check the PHP 8 failure

**Comment by kylekatarnls** [comment]
Sounds like there is a mismatch between doc that mention n/e array as load() parameter:
https://phpseclib.com/docs/rsa#raw-rsa-public-keys

But actually takes string $key as first parameter.

**Comment by bshaffer** [comment]
The error I'm seeing in PHP 8.0:

```
1) Google_AccessToken_VerifyTest::testPhpsecConstants
TypeError: strpos(): Argument #1 ($haystack) must be of type string, array given

/home/runner/work/google-api-php-client/google-api-php-client/vendor/phpseclib/phpseclib/phpseclib/Crypt/EC/Formats/Keys/PKCS1.php:64
/home/runner/work/google-api-php-client/google-api-php-client/vendor/phpseclib/phpseclib/phpseclib/Crypt/Common/AsymmetricKey.php:162
/home/runner/work/google-api-php-client/google-api-php-client/vendor/phpseclib/phpseclib/phpseclib/Crypt/PublicKeyLoader.php:42
/home/runner/work/google-api-php-client/google-api-php-client/src/AccessToken/Verify.php:235
/home/runner/work/google-api-php-client/google-api-php-client/src/AccessToken/Verify.php:105
/home/runner/work/google-api-php-client/google-api-php-client/tests/Google/AccessToken/VerifyTest.php:41
```

**Comment by kylekatarnls** [comment]
Yes @bshaffer I checked the GitHub log yesterday already and was able to reproduce it locally.

I provided a minimal code chunk that reproduces it using the code strictly taken from the documentation that proves it needs to be fixed in phpseclib itself:
https://github.com/phpseclib/phpseclib/pull/1559

**Comment by kylekatarnls** [comment]
PHP 8 support fixed in https://github.com/phpseclib/phpseclib/commit/02fa3b142e34e90c37d53e41b599477d1353c391

**Comment by kylekatarnls** [comment]
PHP 8 fixed with 3.0.2 version.

**Review by bshaffer — APPROVED** [review]

**Comment by Spomky** [comment]
Hi,

Will this change be tagged soon?

**Pull request merged**
