### PR TITLE
Remove redundand and invalid "classmap" in `composer.json`

### PR DESCRIPTION
**Pull request by WinterSilence**
"src/aliases.php" is not classmap

### CODE REVIEW

**Comment by bshaffer** [comment]
The tests fail without this line. I'm not sure why, but I know it is necessary for these classes to function as expected. I believe its because they need to be called when the autoloader is invoked.

**Comment by WinterSilence** [comment]
@bshaffer reason failed tests:
> 1) Google\Tests\Task\ComposerTest::testE2EBCTaskName
Failed asserting that file "/tmp/test-1912002904/vendor/google/apiclient-services/src/YouTube.php" does not exist.

has nothing to do with this PR

**Comment by bshaffer** [comment]
@WinterSilence yes it does, it is happening as a direct result of your PR.

**Comment by WinterSilence** [comment]
@bshaffer :facepalm it's happened because you miss
 `"autoload-dev": {
        "psr-4": {
            "Google\\Tests\\": "tests/Google/"
        },
        "classmap": ["tests/BaseTest.php"]
},
`

**Pull request closed without merging**
