### PR TITLE
chore: drop support for PHP 7.4

### PR DESCRIPTION
**Pull request by bshaffer**

### CODE REVIEW

**Review by Hectorhammett — APPROVED** [review]

**Comment by Hectorhammett** [comment]
The 7.X tests are still running, Should we remove them? What is the protocol here @bshaffer

**Comment by vishwarajanand** [comment]
README also needs to be changed: 
https://github.com/googleapis/google-api-php-client/blob/7e79f3d7be4811f760e19cc4a2c558e04196ec1d/README.md?plain=1#L28

**Comment by vishwarajanand** [comment]
@Hectorhammett that is happening because php7.4 is mentioned in the repo settings. It can be fixed by removing it, but only admin can see/do this change.

**Review by vishwarajanand — APPROVED** [review]
Approving to unblock

**Pull request merged**
