### PR TITLE
Run tests against PHP 7.3+ and check for cross-version support for PHP 5.4+

### PR DESCRIPTION
**Pull request by swissspidy**

### CODE REVIEW

**Comment by jdpedrie** [comment]
Thanks @swissspidy, the proposal makes a lot of sense! We'll need to address the failing tests, but once that gets ironed out I'm good with this.

**Comment by swissspidy** [comment]
Thanks @jdpedrie! Not sure why the tests fail on PHP 5.4 though 🤔 
I suppose it's because of different versions of packages being used. Any hint appreciated.

**Comment by swissspidy** [comment]
Working smoothly now! 🎉

**Comment by swissspidy** [comment]
BTW I also might have a small change ready that could help with the PHP 7.4 failures. Basically, it would run tests on that platform using a newer version of PHPUnit.

**Comment by jdpedrie** [comment]
Looks good to me. Will `7.4snapshot` still be available once 7.4 is officially released?

**Comment by swissspidy** [comment]
In my experience the snapshot builds on Travis would then just be for the 7.4.x alphas. Because for PHP 8 there is the `nightly` version.

**Comment by jdpedrie** [comment]
So once we get to release, we'll need to be sure to update this to `7.4`.

**Comment by swissspidy** [comment]
Ideally, yes :-)

**Pull request merged**
